# 模因地下城 游戏说明配置文件

game_logo_title: |
  ╔═══════════════════════════════════════════════════╗
                      Meme Dungeon
                      模因地下城
  ╚═══════════════════════════════════════════════════╝

game_guide: |
  ╔══════════════════════════════════════════════════════════╗
                          游戏说明                            
  ╚══════════════════════════════════════════════════════════╝

  🎮 游戏玩法:
  • 这是一个基于文字RPG冒险游戏
  • 选择你的角色，探索地下城，与随机对手进行战斗

  ⚔️ 角色属性:
  • 生命值 (Health): 角色的血量，降到0时战败
  • 攻击力 (Attack): 决定造成伤害的基础数值
  • 防御力 (Defense): 减少承受的伤害

  🎯 战斗机制:
  • 攻击伤害 = 攻击力 - 目标防御力

  🏆 胜利条件:
  • 将对手的生命值降到0

dungeon_dm: 库罗斯
dungeon_dm_en: Curro

game_intro: 欢迎来到模因地下城！准备好迎接挑战了吗？

game_exit: 👋 感谢游玩模因地下城！
