# PyBattleLootGame 游戏说明配置文件

game_info:
  title: "PyBattleLootGame 游戏说明"
  content: |
    ╔══════════════════════════════════════════════════════════╗
    ║                      游戏说明                            ║
    ╚══════════════════════════════════════════════════════════╝
    
    🎮 游戏玩法:
    • 这是一个回合制1v1战斗模拟器
    • 选择你的角色，与对手进行战斗
    • 每回合角色会自动攻击对方
    • 战斗持续到有一方生命值归零
    
    ⚔️ 角色属性:
    • 生命值 (Health): 角色的血量，降到0时战败
    • 攻击力 (Attack): 决定造成伤害的基础数值
    • 防御力 (Defense): 减少承受的伤害
    
    🎯 战斗机制:
    • 攻击伤害 = 攻击力 × 随机倍数(0.8-1.2) - 目标防御力
    • 10%概率产生暴击，伤害提升50%
    • 每次攻击至少造成1点伤害
    
    🏆 胜利条件:
    • 将对手的生命值降到0
    • 或在50回合内保持更高的生命值