# PyBattleLootGame 配置文件
# 定义游戏的基础设置和角色属性

# 战斗设置
battle:
  max_rounds: 50
  critical_hit_chance: 0.1
  critical_hit_multiplier: 1.5
  damage_variance_min: 0.8
  damage_variance_max: 1.2

# 显示设置
display:
  health_bar_length: 20
  auto_advance_battle: false
  battle_delay_seconds: 1

# 预设角色属性
characters:
  - name: "剑士"
    health: 100
    attack: 25
    defense: 8
  - name: "法师"
    health: 80
    attack: 35
    defense: 5
  - name: "弓箭手"
    health: 90
    attack: 30
    defense: 6
  - name: "盾卫"
    health: 120
    attack: 20
    defense: 12
  - name: "刺客"
    health: 70
    attack: 40
    defense: 4
  - name: "圣骑士"
    health: 110
    attack: 22
    defense: 10