# PyBattleLootGame 配置文件
# 定义游戏的基础设置和角色属性

# 战斗设置
battle:
  max_rounds: 50
  critical_hit_chance: 0.1
  critical_hit_multiplier: 1.5
  damage_variance_min: 0.8
  damage_variance_max: 1.2

# 显示设置
display:
  health_bar_length: 20
  auto_advance_battle: false
  battle_delay_seconds: 1
